language: clojure
install: cd leiningen-core; lein install; cd ..
script: bin/lein test
branches:
  only:
    - travis-experimenting
notifications:
  irc: "irc.atw-inter.net#aiprog"
jdk:
  - openjdk6
  - openjdk7
  # currently needs some work to pass. MK.
  # - oraclejdk7
